import { StyleSheet } from "react-native";

export const homeStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#f6f1e8",
  },
  authContainer: {
    flexGrow: 1,
    padding: 20,
    justifyContent: "center",
  },
  authCard: {
    backgroundColor: "#fffaf2",
    borderRadius: 24,
    padding: 20,
    gap: 14,
    borderWidth: 1,
    borderColor: "#d9c9ae",
    shadowColor: "#5d4730",
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 3,
  },
  heroRow: {
    gap: 8,
  },
  heroEyebrow: {
    color: "#8a5a2b",
    fontSize: 13,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  heroTitle: {
    color: "#1f2d24",
    fontSize: 28,
    fontWeight: "800",
    lineHeight: 34,
  },
  heroSubtitle: {
    color: "#53645d",
    fontSize: 15,
    lineHeight: 22,
  },
  segmentRow: {
    flexDirection: "row",
    gap: 12,
  },
  fieldBlock: {
    gap: 6,
  },
  fieldLabel: {
    color: "#30423a",
    fontSize: 14,
    fontWeight: "600",
  },
  input: {
    borderWidth: 1,
    borderColor: "#d9c9ae",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: "#ffffff",
    color: "#1f2d24",
    fontSize: 15,
  },
  inputMultiline: {
    minHeight: 110,
    textAlignVertical: "top",
  },
  centerState: {
    flex: 1,
    minHeight: 260,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    padding: 24,
  },
  centerStateTitle: {
    color: "#1f2d24",
    fontSize: 20,
    fontWeight: "800",
  },
  centerStateText: {
    color: "#53645d",
    fontSize: 14,
    textAlign: "center",
    lineHeight: 21,
  },
  listContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 48,
    gap: 16,
  },
  libraryHeader: {
    gap: 16,
    marginBottom: 12,
  },
  libraryHero: {
    backgroundColor: "#fffaf2",
    borderRadius: 24,
    padding: 20,
    gap: 8,
    borderWidth: 1,
    borderColor: "#d9c9ae",
  },
  summaryRow: {
    flexDirection: "row",
    gap: 12,
  },
  summaryCard: {
    flex: 1,
    backgroundColor: "#efe3cd",
    borderRadius: 18,
    padding: 16,
    gap: 6,
  },
  summaryLabel: {
    color: "#7a5b35",
    fontSize: 13,
    fontWeight: "700",
  },
  summaryValue: {
    color: "#1f2d24",
    fontSize: 20,
    fontWeight: "800",
  },
  headerActions: {
    flexDirection: "row",
    gap: 12,
  },
  cardComposer: {
    backgroundColor: "#fffaf2",
    borderRadius: 24,
    padding: 18,
    gap: 12,
    borderWidth: 1,
    borderColor: "#d9c9ae",
  },
  sectionTitle: {
    color: "#1f2d24",
    fontSize: 20,
    fontWeight: "800",
  },
  cardItem: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: "#e3d9c8",
    gap: 12,
  },
  cardTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  cardTitleGroup: {
    flex: 1,
    gap: 4,
  },
  cardTitle: {
    color: "#1f2d24",
    fontSize: 18,
    fontWeight: "800",
  },
  cardMeta: {
    color: "#7a5b35",
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  cardSummary: {
    color: "#445650",
    fontSize: 14,
    fontWeight: "600",
  },
  cardContent: {
    color: "#53645d",
    fontSize: 14,
    lineHeight: 21,
  },
  tagRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  tagChip: {
    backgroundColor: "#edf4ef",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  tagText: {
    color: "#1f5c49",
    fontSize: 12,
    fontWeight: "700",
  },
  emptyState: {
    backgroundColor: "#fffaf2",
    borderRadius: 22,
    padding: 20,
    gap: 8,
    borderWidth: 1,
    borderColor: "#d9c9ae",
  },
  emptyStateTitle: {
    color: "#1f2d24",
    fontSize: 18,
    fontWeight: "800",
  },
  emptyStateText: {
    color: "#53645d",
    fontSize: 14,
    lineHeight: 22,
  },
});
