export const DEFAULT_QUERY_STALE_TIME = 60_000;
export const DEFAULT_QUERY_GC_TIME = 10 * 60_000;

export const LIBRARY_QUERY_STALE_TIME = DEFAULT_QUERY_STALE_TIME;
export const CHAT_LIST_STALE_TIME = 15_000;
export const CHAT_MESSAGES_STALE_TIME = 0;
export const PROCESSING_SOURCE_POLL_INTERVAL = 5_000;

