export const sessionCopy = {
  retry: "重新加载",
  chat: {
    newChatTitle: "新会话",
    unnamedChatTitle: "未命名会话",
    detailTitle: "会话详情",
    selectionAction: "选取消息",
    cancelAction: "取消",
    streamInterruptedTitle: "消息中断",
    sendFailureTitle: "发送失败",
    sendFailureDescription: "这条消息暂时没有发送成功，请稍后再试。",
    abortFailureTitle: "停止失败",
    abortFailureDescription: "暂时无法停止这次生成，请稍后再试。",
    importFailureTitle: "导入失败",
    importFailureDescription: "暂时无法将这些消息导入为知识来源，请稍后再试。",
    importEmptyTitle: "无法导入",
    importEmptyDescription: "请至少选择一条包含有效文本内容的消息。",
    welcomeTitle: "开始新的对话",
    welcomeDescription: "输入你的问题、想法，或者想整理的内容。",
    loadingTitle: "正在加载会话",
    loadingDescription: "请稍等，我们正在同步当前对话内容。",
    errorTitle: "消息加载失败",
    errorDescription: "请稍后再试。",
  },
  sessionList: {
    newChatAction: "新会话",
    loadingTitle: "正在加载会话",
    loadingDescription: "请稍等，我们正在同步你的会话列表。",
    errorTitle: "会话加载失败",
    errorDescription: "请稍后再试。",
    emptyTitle: "暂无会话",
    emptyDescription: "从上方开始一段新的对话吧。",
    itemDescription: "进入对话，继续查看消息或发起新的提问。",
    moreAction: "更多操作",
    deleteAction: "删除",
    deletePendingAction: "删除中…",
    deleteFailureTitle: "删除失败",
    deleteFailureDescription: "暂时无法删除这个会话，请稍后再试。",
  },
} as const;
